name: maxspin
description: |
  An information theoretic approach to detecting spatially varying genes
publications:
  - 10.1016/j.crmeth.2023.100507
project_home: https://github.com/dcjones/maxspin
documentation_home: https://maxspin.readthedocs.io/en/latest/
tutorials_home: https://github.com/dcjones/maxspin/blob/main/tutorial.ipynb
install:
  pypi: maxspin
tags:
  - spatially varying genes
  - spatial autocorrelation
license: MIT
version: v0.1.1
authors:
  - dcjones
test_command: pip install "." && pytest
