fail_fast: false
default_language_version:
    python: python3
default_stages:
    - commit
    - push
minimum_pre_commit_version: 2.16.0
repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.1
      hooks:
          - id: prettier
