name: diffxpy
description: |
    Diffxpy covers a wide range of differential expression analysis scenarios encountered in 
    single-cell RNA-seq scenarios and integrates into scanpy workflows.
project_home: https://github.com/theislab/diffxpy
documentation_home: https://diffxpy.readthedocs.io/en/latest/
tutorials_home: https://diffxpy.readthedocs.io/en/latest/
install:
    pypi: diffxpy
tags:
    - scanpy
license: BSD-3-Clause
version: v0.7.4
authors:
    - davidsebfischer
    - Hoeze
test_command: null
