name: dca
description: |
    A deep count autoencoder network to denoise scRNA-seq data and remove the dropout effect by 
    taking the count structure, overdispersed nature and sparsity of the data into account using 
    a deep autoencoder with zero-inflated negative binomial (ZINB) loss function.
project_home: https://github.com/theislab/dca
documentation_home: https://github.com/theislab/dca/tree/master/docs
tutorials_home: https://github.com/theislab/dca/blob/master/tutorial.ipynb
publications:
    - 10.1038/s41467-018-07931-2
install:
    pypi: dca
tags:
    - autoencoder
    - ZINB
license: Apache-2.0
version: v0.3.1
authors:
    - gokceneraslan
    - ersinpw
    - timoast
    - gamazeps
    - bebatut
    - milescsmith
    - flying-sheep
test_command: null
