name: fava
description: |
  FAVA uses Variational Autoencoders to infer functional associations from
  large-scale scRNA-seq (and proteomics) data.
project_home: https://github.com/mikelkou/fava
documentation_home: https://github.com/mikelkou/fava/blob/main/README.md
tutorials_home: https://github.com/mikelkou/fava/blob/main/How_to_use_favapy_in_a_notebook.ipynb
publications:
  - 10.1101/2022.07.06.499022
  - 10.1093/nar/gkac1000
install:
  pypi: favapy
tags:
  - coexpression networks
  - functional associations
  - variational autoencoders
license: MIT
version: v0.3.9.4
authors:
  - mikelkou
