name: bbknn
description: |
    BBKNN is a fast and intuitive batch effect removal tool that can be directly used in the scanpy workflow.
    It serves as an alternative to scanpy.pp.neighbors(), with both functions creating a neighbour graph
    for subsequent use in clustering, pseudotime and UMAP visualisation.
project_home: https://github.com/Teichlab/bbknn
documentation_home: https://bbknn.readthedocs.io/en/latest/
tutorials_home: https://bbknn.readthedocs.io/en/latest/
publications:
    - https://doi.org/10.1093/bioinformatics/btz625
install:
    pypi: bbknn
tags:
    - scanpy
license: MIT
version: v1.5.1
authors:
    - ktpolanski
    - Jongeun Park
test_command: null
