name: novoSpaRc
description: |
    novoSpaRc predicts locations of single cells in space by solely using 
    single-cell RNA sequencing data. An existing reference database of marker 
    genes is not required, but significantly enhances performance if available.
project_home: https://github.com/rajewsky-lab/novosparc
documentation_home: https://novosparc.readthedocs.io
tutorials_home: https://github.com/rajewsky-lab/novosparc/blob/master/reconstruct_drosophila_embryo_tutorial.ipynb
publications:
    - 10.1038/s41586-019-1773-3
    - 10.1038/s41596-021-00573-7
install:
    pypi: novosparc
tags:
    - spatial reconstruction
    - de novo
license: BSD-3-Clause
version: v0.4.4
authors:
    - mornitzan
    - nukappa
    - nomoriel
    - enessenel
test_command: null
