name: omicverse
description: |
  OmicVerse is the fundamental package for multi omics included bulk and single cell analysis with Python.
  The original name of the omicverse was Pyomic, but we wanted to address a whole universe of transcriptomics,
  so we changed the name to OmicVerse, it aimed to solve all task in RNA-seq.
project_home: https://github.com/Starlitnightly/omicverse
documentation_home: https://omicverse.readthedocs.io/
publications:
  - 10.1101/2023.06.06.543913
install:
  pypi: omicverse
tags:
  - single-cell
  - bulk-rna-seq
  - omics
  - bioinformatics
license: GPL-3.0-only
version: v1.4.12
authors:
  - Starlitnightly
  - DBinary
  - JuliaMYQ
test_command: pip install "." && pytest
