name: CellPhoneDB
description: |
    CellPhoneDB is a publicly available repository of curated receptors, ligands and their interactions in HUMAN.
project_home: https://github.com/ventolab/CellphoneDB
documentation_home: https://decoupler-py.readthedocs.io/en/latest/
tutorials_home: https://decoupler-py.readthedocs.io/en/latest/
publications:
    - 10.1038/s41596-020-0292-x
install:
    pypi: CellPhoneDB
tags:
    - UniProt
    - Ensembl
    - PDB
    - IMEx consortium
    - IUPHAR
license: MIT
version: v3.1.0
authors:
    - chapuzzo
    - mvento
    - luzgaral
    - prete
    - nh3
    - mief
    - evanbiederstedt
    - Nic-Nic
    - boombard
    - zktuong
    - kant
    - rvento
test_command: null
