name: scArches
description: |
  Single-cell architecture surgery (scArches) is a package for reference-based 
  analysis of single-cell data.
project_home: https://github.com/theislab/scarches
documentation_home: https://scarches.readthedocs.io/en/latest/
tutorials_home: https://scarches.readthedocs.io/en/latest/mvTCR_borcherding.html
publications:
  - 10.1038/s41587-021-01001-7
install:
  pypi: scArches
tags:
  - transfer learning
license: BSD-3-Clause
version: v0.5.0
authors:
  - mn7697np
  - M0hammadL
  - Naghipourfar
  - Koncopd
  - Cottoneyejoe95
  - aidinbii
  - MohsenNaghipourfar
  - lcmmichielsen
  - mbuttner
  - EliHei2
  - MatinKhajavi
  - MohsenNp
  - DeepOzean
  - cuongqn
  - Zethson
  - Hrovatin
  - evanbiederstedt
test_command: pip install "." && pytest
