name: cNMF
description: |
    cNMF is an analysis pipeline for inferring gene expression programs from single-cell RNA-Seq (scRNA-Seq) data.
project_home: https://github.com/dylkot/cNMF
documentation_home: http://docs.mesmerizelab.org/en/v0.6.1/user_guides/viewer/modules/cnmf.html
tutorials_home: https://github.com/dylkot/cNMF/tree/master/Tutorials
publications:
    - 10.7554/eLife.43803
install:
    pypi: cnmf
tags:
    - GRP
license: MIT
version: v1.3.4
authors:
    - dylkot
test_command: null